# Generated by Django 2.2 on 2020-07-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu',
            field=models.CharField(default=1, max_length=40, verbose_name='CPU'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='ram',
            field=models.PositiveIntegerField(default=1, verbose_name='RAM'),
            preserve_default=False,
        ),
    ]
